# Generated by Django 5.1.5 on 2025-01-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
